### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by 99letters** [karaage0703/code-cooker#1]
すいません。教えて欲しいのですが、
下記部分で、エクセルのファイルもあげているのですが、Youtubeのようにうまくいかずerror codeが出てきてしまいます。
からあげさんのを見ているとそのようなエラーにならないので、何かお分かりでしたらご教授いただくこと可能でしょうか？

%%_ sample_excel.xlsx
アップロードしたExcelファイルの金額を月ごとに集計して棒グラフにしてください。
<img width="1231" alt="スクリーンショット 2024-05-02 17 12 28" src="https://github.com/karaage0703/code-cooker/assets/75833079/a2069c9f-521b-434d-8f79-a156f7f01ad7">

エラー内容
I am Claude
Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I am Claude
Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I am Claude
Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I am Claude
Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
I am Claude
Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}
---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
[<ipython-input-6-5eb6c771bdcb>](https://localhost:8080/#) in _(line, cell)
     52             if AI_TYPE == "ANTHROPIC":
---> 53                 response = chat_claude(prompt_w_history, system_prompt)
     54             if AI_TYPE == "PHI3":

9 frames
BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-6-5eb6c771bdcb>](https://localhost:8080/#) in _(line, cell)
     59         except Exception as e:
     60             print(e)
---> 61             time.sleep(3)
     62             continue
     63 

KeyboardInterrupt:

**Comment by 99letters** [comment]
立て続けにすいません。
Open AIだと動きはするのですが、下記のようなエラーが出るので私のエクセル内容があまりよろしくないような気がしてきました。ここはからあげさんの著書の本を購入して再度勉強しようと思います。
<img width="1122" alt="スクリーンショット 2024-05-02 17 25 35" src="https://github.com/karaage0703/code-cooker/assets/75833079/02b54996-6b3a-44e3-bd7f-8f1993939283">


I am GPT
APIからの応答: まずはExcelファイルを読み込んでデータの構造と最初のいくつかのデータを確認します。データの確認ができたら、金額を月ごとに集計し、棒グラフを生成します。ここで用いるライブラリがすでにインストールされている前提で進めますが、万が一不足している場合はインストールが必要です。

```python
import pandas as pd
import matplotlib.pyplot as plt

try:
    # pandasでExcelファイルを読み込む
    df = pd.read_excel('sample_excel.xlsx', engine='openpyxl')
    # データの概要を表示
    print(df.head())
    print(df.info())
    
    # groupbyを使って月ごとに金額を集計
    df['月'] = pd.to_datetime(df['日付']).dt.month  # 日付から月を抽出
    monthly_sums = df.groupby('月')['金額'].sum()
    
    # 集計結果の確認
    print(monthly_sums)
    
    # 棒グラフの作成
    monthly_sums.plot(kind='bar', color='skyblue', title='月ごとの金額集計')
    plt.xlabel('月')
    plt.ylabel('金額')
    plt.show()
except ImportError as e:
    print("必要なライブラリがインストールされていません。以下のコマンドを実行してください：")
    print("pip install pandas openpyxl matplotlib")
except FileNotFoundError as e:
    print("ファイルが見つかりません。ファイルパスを再確認してください。")
except Exception as e:
    print(f"エラーが発生しました: {e}")
```

このコードはExcelファイルを読み込み、日付から月情報を抽出して月ごとに金額を集計し、その結果を棒グラフで表示します。エラーがあればそれに対応する指示が表示されるようになっています。
Result:
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN   
1         NaN        NaN        NaN        NaN        NaN        NaN   
2         NaN         1月         2月         3月         4月         5月   
3         NaN     32000円     28000円     14200円     14200円     14200円   
4         NaN     32000円        NaN        NaN        NaN        NaN   

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  
0        NaN        NaN        NaN        NaN         NaN  
1        NaN        NaN        NaN        NaN         NaN  
2         6月         7月         8月         9月         10月  
3     14200円     14200円     14200円     14200円      14200円  
4        NaN        NaN        NaN        NaN         NaN  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   7 non-null      object 
 2   Unnamed: 2   2 non-null      object 
 3   Unnamed: 3   2 non-null      object 
 4   Unnamed: 4   2 non-null      object 
 5   Unnamed: 5   2 non-null      object 
 6   Unnamed: 6   2 non-null      object 
 7   Unnamed: 7   2 non-null      object 
 8   Unnamed: 8   2 non-null      object 
 9   Unnamed: 9   2 non-null      object 
 10  Unnamed: 10  2 non-null      object 
dtypes: float64(1), object(10)
memory usage: 920.0+ bytes
None
エラーが発生しました: '日付'

コードの実行が完了しました。

**Comment by karaage0703** [comment]
@99letters
質問ありがとうございます。
プロトタイプなので説明色々足りずすみません。

プロンプトの入力、順番にルールがあったりするので、以下のように一度プロンプトの履歴の初期化をしてから実行してもらえるとよいかもしれません。

```
prompt_w_history = []
```

あと、エクセルの方は、うまく実行できているような気がします。
データを表示してプロンプトに読み込めているので、もう一度実行すると、何かしら表示してくれるかもしれません。

**Comment by 99letters** [comment]
@karaage0703 
からあげさんありがとうございます！
おかげさまでうまくいきましたー！すごく嬉しいです！
